"""公开 Iris 当前使用的领域异常。"""

from .exceptions import (
    # HITL
    HITLCheckpointInvalidError,
    HITLConflictError,
    HITLResponseMismatchError,
    IrisAPIConnectionError,
    IrisAuthenticationError,
    # Runtime control
    IrisCancellationRequestedError,
    # Core / Config
    IrisConfigError,
    IrisContextError,
    IrisError,
    IrisHITLError,
    # Lifecycle / Run
    IrisLifecycleSchemaError,
    # Memory
    IrisMemoryError,
    # Provider
    IrisProviderError,
    IrisProviderStreamError,
    IrisProviderStreamInterruptedError,
    IrisProviderStreamProtocolError,
    IrisRateLimitExceededError,
    IrisRunConflictError,
    IrisRunError,
    IrisRunNotFoundError,
    IrisRunObservationTimeoutError,
    IrisRunPersistenceError,
    IrisRunRecoveryError,
    IrisRunStateError,
    # Skill
    IrisSkillError,
    IrisSkillFormatError,
    IrisSkillNotFoundError,
    IrisSkillPathError,
    # Template
    IrisTemplateError,
    IrisTemplateNotFoundError,
    # Tool
    IrisToolError,
    IrisToolExecutionError,
    IrisToolNotFoundError,
    IrisToolValidationError,
    IrisValidationError,
)

__all__ = [
    "IrisError",
    "IrisCancellationRequestedError",
    "IrisConfigError",
    "IrisContextError",
    "IrisSkillError",
    "IrisSkillFormatError",
    "IrisSkillPathError",
    "IrisSkillNotFoundError",
    "IrisValidationError",
    "IrisHITLError",
    "HITLResponseMismatchError",
    "HITLConflictError",
    "HITLCheckpointInvalidError",
    "IrisProviderError",
    "IrisProviderStreamError",
    "IrisProviderStreamInterruptedError",
    "IrisProviderStreamProtocolError",
    "IrisAPIConnectionError",
    "IrisRateLimitExceededError",
    "IrisAuthenticationError",
    "IrisToolError",
    "IrisToolNotFoundError",
    "IrisToolExecutionError",
    "IrisToolValidationError",
    "IrisMemoryError",
    "IrisLifecycleSchemaError",
    "IrisRunConflictError",
    "IrisRunNotFoundError",
    "IrisRunObservationTimeoutError",
    "IrisRunPersistenceError",
    "IrisRunRecoveryError",
    "IrisRunError",
    "IrisRunStateError",
    "IrisTemplateError",
    "IrisTemplateNotFoundError",
]
