"""跨 Run 目标的领域模型、状态服务与原子存储契约。"""

from .config import GoalConfig
from .driver import GoalDriver
from .models import (
    GoalAdmission,
    GoalChanged,
    GoalContinuationIntent,
    GoalControlDisposition,
    GoalControlResult,
    GoalCreateInput,
    GoalDecision,
    GoalEditInput,
    GoalProcessState,
    GoalReason,
    GoalRef,
    GoalReport,
    GoalRunBinding,
    GoalSettlement,
    GoalSnapshot,
    GoalStatus,
    GoalView,
)
from .service import GoalService
from .session import GoalControlPort, GoalSession
from .store import (
    AdmitGoalRun,
    ClearGoal,
    CompleteGoal,
    CreateGoal,
    EditGoal,
    GoalStore,
    GoalUpdate,
    PauseGoal,
    ResumeGoal,
)

__all__ = [
    "GoalDriver",
    "GoalChanged",
    "GoalContinuationIntent",
    "GoalControlDisposition",
    "GoalControlResult",
    "GoalCreateInput",
    "GoalEditInput",
    "GoalControlPort",
    "GoalSession",
    "GoalService",
    "GoalConfig",
    "GoalStatus",
    "GoalDecision",
    "GoalRef",
    "GoalReason",
    "GoalReport",
    "GoalRunBinding",
    "GoalSettlement",
    "GoalSnapshot",
    "GoalAdmission",
    "GoalProcessState",
    "GoalView",
    "CreateGoal",
    "EditGoal",
    "PauseGoal",
    "ResumeGoal",
    "CompleteGoal",
    "ClearGoal",
    "GoalUpdate",
    "AdmitGoalRun",
    "GoalStore",
]
